# Generated by Django 2.2.2 on 2019-07-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='head',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
