# Generated by Django 2.2.2 on 2019-07-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='head',
            new_name='title',
        ),
    ]
