# Generated by Django 2.2.2 on 2019-12-29 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190705_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
